// Autogenerated file, please do not modify this manually!

import { type CollectionEntry, importMarkdownFiles } from "@adaliszk/content-manager/internal";

export type PageKeys = "homepage";

export type PageSchema = {
    title: string;
    description?: string | undefined;
    keywords?: string[] | undefined;
    image?: string | undefined;
};

export type PageEntry = CollectionEntry<PageSchema>;

export const pages = importMarkdownFiles<PageKeys, PageEntry>({
    homepage: {
        id: "6422e1173df2b7cc23689baa8c",
        name: "homepage",
        path: ".",
        file: "homepage.mdx",
        ext: ".mdx",
        langCode: undefined,
        sortIndex: 0,
        createdAt: new Date("2024-06-03T10:33:59.933Z"),
        updatedAt: new Date("2024-06-03T10:34:38.074Z"),
        updatedBy: undefined,
        updateMessage: "undefined",
        updateCommit: "undefined",
        ...(await import("./homepage.mdx")),
    },
});

export const _byId = new Map<string, PageEntry>(
    Array.from(pages.values()).map((entry: PageEntry) => [entry.id, entry]),
);
