# -----------------------------------------------------------------------------
name: Code Quality
on:
  workflow_dispatch: {}
  pull_request: {}
  push: {}

# -----------------------------------------------------------------------------
jobs:

  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: ./.github/actions/setup-env
      - name: 'Qodana Scan'
        uses: jetbrains/qodana-action@v2024.1
        env:
          QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }}
      - uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ runner.temp }}/qodana/results/qodana.sarif.json

  turbo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: ./.github/actions/setup-env
      - run: pnpm lint