# -----------------------------------------------------------------------------
name: Code Quality
on:
  workflow_dispatch: {}
  pull_request: {}
  push: {}

# -----------------------------------------------------------------------------
jobs:

  qodana:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: ./.github/actions/setup-env
      - uses: JetBrains/qodana-action@v2024.1
        env: { QODANA_TOKEN: ${{ secrets.QODANA_TOKEN }} }

  turbo:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with: { fetch-depth: 0 }
      - uses: ./.github/actions/setup-env
      - run: pnpm lint